### ISSUE TITLE
Does the API support brackets voice stylization? How does it affect pricing?

### ISSUE THREAD

**Issue by Nowado** [metavoicexyz/tortoise-tts-modal-api#9]
Tortoise supports stylization with 'prompting', as in https://github.com/neonbjb/tortoise-tts#prompt-engineering. I can't find any mention about it in your tool and you seem to price based on characters - does that work, how?

**Comment by vatsalaggarwal** [comment]
Yes, you can do the exact same thing, and it'll work.

Pricing: We charge per second of compute, not per character. Adding 'prompting' increases the characters, so it takes the model longer to process, so it will likely increase cost but this would be try on any hardware.
